name: 🎉 Release
on:
  push:
    tags:
      - "*"
jobs:
  prepare:
    name: 👷 Prepare
    runs-on: macos-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
      - name: 🐣 Create Release folder on Github
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false

  release-osx:
    name: 🍎 Release on MacOS
    runs-on: macos-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2

      - name: 🧑‍🔧 Build Release
        run: cargo build --release && make zip-mac

      - name: ⬆️ Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: 🧮 Set SHA
        id: shasum
        run: |
          echo ::set-output name=sha::"$(shasum -a 256 target/release/continuous-delivery-mac.tar.gz | awk '{printf $1}')"

      - name: 🚀 Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ needs.prepare.outputs.upload_url }}
          asset_path: target/release/continuous-delivery-mac.tar.gz
          asset_name: continuous-delivery-mac.tar.gz
          asset_content_type: application/gzip

      - name: 🍺 Bump Brew
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}
        run: |
          brew tap tgotwig/homebrew-continuous-delivery
          brew bump-formula-pr -f --version=${{ steps.get_version.outputs.version }} --no-browse --no-audit \
          --sha256=${{ steps.shasum.outputs.sha }} \
          --url='https://github.com/tgotwig/continuous-delivery/releases/download/${{ steps.get_version.outputs.version }}/continuous-delivery-mac.tar.gz' \
          tgotwig/homebrew-continuous-delivery/continuous-delivery

  release-linux:
    name: 🐧 Release on Linux
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2

      - name: 🧑‍🔧 Build Release
        run: cargo build --release && make zip-linux

      - name: ⬆️ Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: 🧮 Set SHA
        id: shasum
        run: |
          echo ::set-output name=sha::"$(shasum -a 256 target/release/continuous-delivery-linux.tar.gz | awk '{printf $1}')"

      - name: 🚀 Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ needs.prepare.outputs.upload_url }}
          asset_path: target/release/continuous-delivery-linux.tar.gz
          asset_name: continuous-delivery-linux.tar.gz
          asset_content_type: application/gzip

      - name: 🏝 Set git config
        run: |
          git config --global user.email "github@tomasu.mozmail.com"
          git config --global user.name "Thomas Gotwig"

      - name: Install Linuxbrew
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" < /dev/null

      - name: 🍺 Bump Brew
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}
        run: |
          brew tap tgotwig/homebrew-linux-continuous-delivery
          brew bump-formula-pr -f --version=${{ steps.get_version.outputs.version }} --no-browse --no-audit \
          --sha256=${{ steps.shasum.outputs.sha }} \
          --url='https://github.com/tgotwig/continuous-delivery/releases/download/${{ steps.get_version.outputs.version }}/continuous-delivery-linux.tar.gz' \
          tgotwig/homebrew-linux-continuous-delivery/continuous-delivery
